### PR TITLE
ML-346 Seg Fault with zero matrix

### PR DESCRIPTION
**Pull request by RogerDev**
Fix seg fault with zero A matrix and non-zero B and C
Fix corresponding problem (latent) in solve
Enable test case in Multiply test
Add zero matrix test cases in Solve test
Add zero matrix test cases in Factor

### CODE REVIEW

**Comment by richardkchapman** [comment]
Needs rebasing for a clean merge...

@ghalliday Can you take a look at this to check it's efficient as well as correct

**Comment by johnholt** [comment]
How much (any?) parameter checking should be added to the BLAS wrappers?  The wrappers were in a position to to check the array lengths against the dimension parameters to see if they made sense and provide a sensible result.  This check is not trivial because working on a portion of the arrays is perfectly valid.

**Comment by johnholt** [comment]
@RogerDev  Can you resolve the conflict and amend your commit soon?  I need the updated version.

**Comment by johnholt** [comment]
@RogerDev  We really want to have just one commit.  Please use rebase -i to squash your 3 commits into one commit and push that to origin.

**Pull request closed without merging**
